env:
  global:
    - secure: "aMCbPcvDaUgEpLgck6t7fI3NGgi82Ws84DP81v/UTXFVGMSfL6vc3fvjrKx63TRlXX0FCi78HVon8Fyg7MSOREO/aA1kao6Grb+I9yd4VlOOeEvyxfxVsGnhUkZ94584zAc7rol7eCcqe9UvutQ4JIgTOAEEV3qOvDn1Nsg1tS4="

sudo: false

language: android

jdk:
  - oraclejdk8

branches:
  only:
    - develop
    - master

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19

addons:
  coverity_scan:

    project:
      name: "federicoiosue/Omni-Notes"
      version: 5.3.0
      description: "Open-source note-taking application for Android"

    notification_email: federico.iosue@gmail.com

    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew build"

    branch_pattern: coverity_scan

# Build
script: ./gradlew --stacktrace clean build


