sudo: true
language: android
dist: trusty
install: true
addons:
  sonarcloud:
    organization: federicoiosue-github
    token: $SONAR_TOKEN
    branches:
    - develop
jdk:
- oraclejdk8
branches:
  only:
  - develop
  - master
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
script: 
  - ./gradlew clean build jacocoTestReport
  - sonar-scanner
